exclude: '^(doc)/'
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: check-ast
      - id: check-json
      - id: flake8
        additional_dependencies:
          - flake8-colors
      - id: trailing-whitespace

  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
