sudo: false
distro: trusty
addons:
  chrome: stable
before_install:
  - wget -N https://chromedriver.storage.googleapis.com/2.33/chromedriver_linux64.zip -P /tmp
  - mkdir /tmp/chromedriver
  - unzip /tmp/chromedriver_linux64.zip -d /tmp/chromedriver
  - export PATH=$PATH:/tmp/chromedriver/
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
cache: pip
install: pip install tox-travis
env:
  - TOXENV="py3, flake8"
script: tox
