# qstode

version: "3.2"
services:
  qstode:
    build: .
    image: qstode:latest
    restart: always
    ports:
      # HOST[:HOST_PORT]:CONTAINER
      - "127.0.0.1:5000:5000"
    volumes:
      - .:/app/src
    environment:
      SQLALCHEMY_DATABASE_URI: mysql+mysqlconnector://qstode_user:capriolo@mysql/qstode
  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./qstode/static:/app/src/qstode/static
    ports:
      - "127.0.0.1:8080:80"
  mysql:
    image: mysql:5.7
    logging:
      driver: none
    environment:
      MYSQL_ROOT_PASSWORD: scassacazzi
      MYSQL_DATABASE: qstode
      MYSQL_USER: qstode_user
      MYSQL_PASSWORD: capriolo
    volumes:
      - ../qstode-data/qstode-mysql:/var/lib/mysql
